### PR TITLE
adding iframe google maps favicon

### PR DESCRIPTION
**Pull request by Acrosave**
in this part adding a favicon in the website, and then adding a buttom with google maps iframe

### CODE REVIEW

**Review by edwincaipa — APPROVED** [review]
Excelente

**Review by edwincaipa — APPROVED** [review]
bien

**Review by edwincaipa — APPROVED** [review]
aprobado

**Review by edwincaipa — APPROVED** [review]
realizado

**Comment by Acrosave** [comment]
listo ya quedo

**Pull request merged**
